---
title: The `Processor`
jupyter: python3
---


> The base class for all notebook processors


<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `class Processor` {#nbquarto.processor.Processor}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L22){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`notebook`**`: AttributeDictionary`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">

Base class for all notebook processors.
Any processors should inherit this class.

When writing a processor, you can override methods that
modify the content of a cell with the `process_cell` function.

The class stores the entire notebook in the `notebook`
attribute.

When using a processor, simply call the class and pass
in a single cell.

Example:

```python
class BasicProcessor(Processor):
    "A basic processor that adds a comment to the top of a cell"
    directive = "process"

    def process(self, cell):
        cell.source = f"# This code has been processed!\n{cell.source}"
```

</div><div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">
#### `has_directives` {#nbquarto.processor.Processor.has_directives}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L63){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`cell`**`: AttributeDictionary`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">

Checks if `cell` contains any directives in `self.directives`

</div></div>
<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">
#### `process` {#nbquarto.processor.Processor.process}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L69){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`cell`**`: AttributeDictionary`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **cell** (`AttributeDictionary`) --
  A cell from a Jupyter Notebook

A function to apply on a cell. Should use `self.has_directives`
to see if the processor should be applied



Example:
```python
def process(self, cell):
    if self.has_directives(self, cell):
        cell.source = "Found a directive!"
```

</div></div>
<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">
#### `process_cell` {#nbquarto.processor.Processor.process_cell}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L87){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`cell`**`: AttributeDictionary`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **cell** (`AttributeDictionary`) --
  A cell from a Jupyter Notebook

Applies the processor to a cell if the cell is of the
correct type and contains the correct directive



</div></div>

</div>

<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `class RawPostProcessor` {#nbquarto.processor.RawPostProcessor}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L110){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`content`**`: str`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">

A processor class which deals with modifying the raw `.qmd` files
directly. These are ran *after* the notebook has been processed
and converted to a `.qmd` file.

Similar to the `Processor` class, you should implement a
`process` function to be called, however here it will
just always be called and should modify the raw string
text, which is stored in `self.content`.

Will **always** be ran on each notebook if enabled for the
project.

</div><div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">
#### `process` {#nbquarto.processor.RawPostProcessor.process}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L135){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
()
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">

A function to apply `self.content`.

Example:
```python
def process(self):
    self.content = f'Founda  directive!\n{self.content}'
```

</div></div>

</div>

<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `class NotebookProcessor` {#nbquarto.processor.NotebookProcessor}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L154){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`path`**`: str = None`, **`processors`**`: list = []`, **`notebook`**`: AttributeDictionary = None`, **`config`**`: dict = {}`, **`debug`**`: bool = False`, **`remove_directives`**`: bool = True`, **`process_immediately`**`: bool = False`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **path** (`str`, *optional*, defaults to None) --
  The path to the notebook
- **processors** (`list`, *optional*, defaults to `[]`) --
  A list of functions to apply to the notebook
- **notebook** (`AttributeDictionary`, *optional*, defaults to None) --
  An object representing all the cells in a Jupyter Notebook.
  If None, will be loaded from path
- **processor_args** (`dict`, *optional*, defaults to `{}`) --
  A dictionary of arguments to pass to a given processor.
  Should be structured such as: `{"processor_name: {"argument_name": argument_value}}`
- **debug** (`bool`, *optional*, defaults to `False`) --
  Whether to print debug statements
- **remove_directives** (`bool`, *optional*, defaults to `True`) --
  Whether to remove directives from each cell after processing
- **process_immediately** (`bool`, *optional*, defaults to `False`) --
  Whether to process the notebook after initialization

Processes notebook cells and comments in a notebook



</div><div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">
#### `process_cell` {#nbquarto.processor.NotebookProcessor.process_cell}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L200){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`processor`**`: callable`, **`cell`**`: AttributeDictionary`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **processor** (`callable`) --
  A function to apply to a notebook cell's content
- **cell** (`AttributeDictionary`) --
  A cell from a Jupyter Notebook

Processes a single cell of a notebook. Should not be called
explicitly and instead a user should use `process_notebook`



</div></div>
<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">
#### `process_notebook` {#nbquarto.processor.NotebookProcessor.process_notebook}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/processor.py#L218){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
()
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">

Processes the content of the notebook

</div></div>

</div>

