---
title: Notebook Utilities
jupyter: python3
---


> Functions to help with processing of notebooks. Most come from `nbdev`


<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `class NotebookCell` {#nbquarto.notebook.NotebookCell}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/notebook.py#L22){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`index`**`: int`, **`cell`**`: dict`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">

A cell for a Jupyter Notebook

</div><div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">
#### `set_source` {#nbquarto.notebook.NotebookCell.set_source}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/notebook.py#L40){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`source`**`: list`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **source** (`list`) --
  The source of the cell as a list of strings

Sets the source attribute of the cell as a string and removes parsed directives



</div></div>

</div>

<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `nbquarto.notebook.dict2notebook` {#nbquarto.notebook.dict2notebook}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/notebook.py#L59){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`d`**`: dict = None`, **`**kwargs`**)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **d** (`dict`, *optional*, defaults to None) --
  A dictionary to convert

Converts dictionary `d` to an `AttributeDictionary`



</div>
</div>

<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `nbquarto.notebook.read_notebook` {#nbquarto.notebook.read_notebook}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/notebook.py#L72){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`path`**`: str`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **path** (`str`) --
  The path to the Jupyter Notebook

Reads a Jupyter Notebook from a filepath



</div>
</div>

<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `nbquarto.notebook.write_notebook` {#nbquarto.notebook.write_notebook}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/notebook.py#L86){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`notebook`**`: AttributeDictionary`, **`path`**`: str`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **notebook** (`AttributeDictionary`) --
  An object representing all the cells in a Jupyter Notebook
- **path** (`str`) --
  The path to the Jupyter Notebook

Writes the contents of `notebook` to `path`



</div>
</div>

<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `nbquarto.notebook.new_notebook` {#nbquarto.notebook.new_notebook}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/notebook.py#L126){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`cells`**`: list = []`, **`metadata`**`: dict = {}`, **`nbformat`**`: int = 4`, **`nbformat_minor`**`: int = 5`)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **cells** (`list` of `NotebookCell`, *optional*, defaults to []) --
  A list of cells to make up the notebook
- **metadata** (`dict`, *optional*, defaults to &lcub;}) --
  Metadata for the notebook
- **nbformat** (`int`, *optional*, defaults to 4) --
  The nbformat of the notebook
- **nbformat_minor** (`int`, *optional*, defaults to 5) --
  The minor nbformat version of the notebook

Creates a new empty notebook



</div>
</div>

<div style="background:#f7f7f7; border:2px solid #5a5a5a; border-top-width:2px; border-left-width: 2px; border-top-left-radius: 0.75rem; margin-top: 2rem; margin-bottom: 1.5rem; padding-left: 1rem; padding-right: .5rem;">

### `nbquarto.notebook.make_cell` {#nbquarto.notebook.make_cell}
[\<source\>](https://github.com/muellerzr/nbquarto/blob/main/src/nbquarto/notebook.py#L143){style="float:right;font-size:.875rem;"}
<p style="font-size:.875rem;line-height:1.25rem;">
(**`text`**`: str`, **`cell_type`**`: str = 'code'`, **`**kwargs`**)
</p>

<div style="font-size:.875rem;line-height:1.25rem;margin-bottom:1.25em; margin-top:1.25em; padding_bottom:0;">**Parameters:**

- **text** (`str`) --
  The source code for the cell
- **cell_type** (`str`, *optional*, defaults to "code") --
  The type of cell to make, must be one of "code", "markdown", or "raw"
  kwargs --
  Additional arguments to pass to the cell, such as `metadata`

Makes a blank notebook cell



</div>
</div>

